<a href="https://colab.research.google.com/github/Tejabhai2002/Sale_Prediction_using_LogisticRegression/blob/main/SalesPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
#useful for loading the dataset
import numpy as np #to perform array

choose the dataset from local directory

In [16]:
from google.colab import files
uploaded = files.upload()

Saving SalePrediction.csv to SalePrediction.csv


load dataset

In [17]:
dataset = pd.read_csv('SalePrediction.csv')
print(dataset)

     Age   Salary  Prediction
0     45    51236           0
1     62   421656           1
2     46   854621           0
3     42   632154           1
4     12   956545           1
..   ...      ...         ...
394   51    46566           0
395   62   846532           1
396   53  3213165           1
397   85   512200           0
398   23   320000           0

[399 rows x 3 columns]


summarised the data

In [18]:
print(dataset.shape) # no. of rows and coloumns
print(dataset.head(5))
print(dataset.tail(5))

(399, 3)
   Age  Salary  Prediction
0   45   51236           0
1   62  421656           1
2   46  854621           0
3   42  632154           1
4   12  956545           1
     Age   Salary  Prediction
394   51    46566           0
395   62   846532           1
396   53  3213165           1
397   85   512200           0
398   23   320000           0


segragation of data

In [19]:
X = dataset.iloc[:,:-1].values
X

array([[     45,   51236],
       [     62,  421656],
       [     46,  854621],
       [     42,  632154],
       [     12,  956545],
       [     65,  423365],
       [     52,  855258],
       [     33,  654216],
       [     11,  520000],
       [     65,  546523],
       [     74,  121311],
       [     54,  100213],
       [     12,  254621],
       [     46, 3000121],
       [     85,  521230],
       [     95,  956230],
       [     42,  754210],
       [     62, 8520012],
       [     13,  966511],
       [     52, 2130213],
       [     85,  220022],
       [     74,  651230],
       [     65,  325120],
       [     42, 3200023],
       [     25,  651232],
       [     22,   84655],
       [     21,  564165],
       [     23,  891244],
       [     29,  854265],
       [     25,  123515],
       [     27,  111113],
       [     75,  845631],
       [     45, 5641335],
       [     65, 8465132],
       [     66,   51233],
       [     88,   54651],
       [     44,  845125],
 

In [20]:
Y = dataset.iloc[:,-1].values
Y

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,

splitting dataset into train and test

In [21]:
!pip install scikit-learn

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size= 0.25, random_state=0)

Feature scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-0.04374852 -0.41172143]
 [ 0.00434268 -0.41222728]
 [-0.28420452 -0.50011181]
 [ 0.86998429  2.36167893]
 [ 0.34098109 -0.50004651]
 [-0.90939013 -0.34821945]
 [ 1.3989875  -0.49995454]
 [ 0.10052508  1.28369784]
 [-1.05366373  3.24508704]
 [ 0.05243388 -0.50058225]
 [ 0.48525469 -0.21086667]
 [ 0.24479869 -0.25844809]
 [ 1.5913523  -0.34882647]
 [ 1.0623491  -0.34826084]
 [-1.05366373 -0.60880942]
 [-1.87121414 -0.20800171]
 [ 1.3508963  -0.24350244]
 [ 0.10052508 -0.41172143]
 [-0.90939013 -0.34229178]
 [ 0.48525469 -0.50011181]
 [-0.47656932 -0.63394339]
 [-1.43839333 -0.49822774]
 [-0.38038692  3.24508704]
 [ 0.67761949 -0.25886243]
 [ 0.14861629 -0.34882647]
 [ 0.48525469 -0.34821945]
 [ 0.62952829 -0.49822774]
 [-1.05366373 -0.38807558]
 [ 0.00434268 -0.34821945]
 [-0.42847812 -0.39641203]
 [ 0.05243388 -0.59664228]
 [-0.42847812 -0.23654329]
 [ 0.38907229 -0.04010877]
 [-0.33229572  2.36167893]
 [ 1.5913523   3.27032448]
 [-0.28420452 -0.50011181]
 [-1.91930534 -0.40345625]
 

Training

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [30]:
age = int(input("enter new customer's age"))
sal = int(input("enter new customer's salary"))
newCust = [[age, sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer Will buy this product")
else:
  print("Customer won't buy")

enter new customer's age21
enter new customer's salary900000
[0]
Customer won't buy


prediction of the product will get buy or not

In [25]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]]


evaluating model confusion matrix

In [26]:
from sklearn.metrics import confusion_matrix , accuracy_score
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test , y_pred)

print ("Confusion Matrix:")
print(cm)

print("Accuracy of the model :{0}% ".format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix:
[[49 12]
 [37  2]]
Accuracy of the model :51.0% 
